### ISSUE TITLE
Cannot retrieve key from NSUserDefaults

### ISSUE THREAD

**Issue by albertosottile** [beeware/rubicon-objc#135]
I am trying to detect from Python if the OS interface is set on Light or Dark mode. I wanted to use the code reported [here](https://stackoverflow.com/questions/25207077/how-to-detect-if-os-x-is-in-dark-mode) for Objective C/Swift and [here](https://stackoverflow.com/questions/54701288/detect-dark-mode-in-macos-from-python) for pyobjc, basically

`NSString *osxMode = [[NSUserDefaults standardUserDefaults] stringForKey:@"AppleInterfaceStyle"];`

So, I installed rubicon-objc and executed the following code:
```
>>> from rubicon.objc import ObjCClass
>>> NSUserDefaults = ObjCClass("NSUserDefaults")
>>> print(NSUserDefaults.standardUserDefaults.stringForKey('AppleInterfaceStyle'))
None
```
In contrast, everything works by running the code provided in the pyobjc post:
```
>>> from Foundation import NSUserDefaults
>>> NSUserDefaults.standardUserDefaults().stringForKey_('AppleInterfaceStyle')
'Dark'
```

This is the first time I try rubicon-objc, so I assume I am doing something wrong. Can you help me? Thanks.

**Comment by dgelessus** [comment]
Interesting. I haven't updated to macOS 10.14 yet, so I can't test this specific key, but I can look up other system defaults:

```python
>>> NSUserDefaults.standardUserDefaults.stringForKey("AppleMeasurementUnits")
<rubicon.objc.collections.ObjCStrInstance 0x110073240: __NSCFString at 0x7faa9c0c6820: Centimeters>
```

Do other defaults keys work for you with Rubicon, or are all of them broken? If you look at `NSUserDefaults.standardUserDefaults.dictionaryRepresentation()` using Rubicon, do you see the `AppleInterfaceStyle` key in that dictionary?

**Comment by albertosottile** [comment]
As expected, I was doing something wrong, but not in rubicon-objc at least. It turns out that the key is set **only** when the Dark mode is enabled, and unset when the usual Light mode is enabled. 

Repeating the test with pyobjc did not show the key either, so I figured out the problem. Setting the theme back to Dark and running rubicon-objc again correctly gives:

`>>> NSUserDefaults.standardUserDefaults.stringForKey('AppleInterfaceStyle')
<rubicon.objc.collections.ObjCStrInstance 0x10ffce198: NSTaggedPointerString at 0x5d9715df945086a3: Dark>`

Thanks for your help.
