### ISSUE TITLE
Integration Rubicon inside iOS app that includes Python-Apple support library

### ISSUE THREAD

**Issue by AnissaHum** [beeware/rubicon-objc#151]
Hello,

I am trying to use Rubicon inside an iOS app that has been created thanks to the cookie cutter Python-iOS-template. Inside my Python code, I am trying to import Rubicon with the following line: `from rubicon.objc import ObjCClass`.
This line fails, which makes me think that rubicon is not installed on the device. How can I install Rubicon on my iOS app ?

Thank you for your answer.

**Comment by freakboy3742** [comment]
Hi @AnissaHum!

The Python-iOS-template contains an app_packages directory; you can use that folder as an install target, and use pip to install rubicon-objc into that folder:
```
python -m  pip install --target=/path/to/project/app_packages rubicon-objc 
```
Alternatively, you can use [Briefcase](https://github.com/beeware/briefcase) to manage the installation process for you. See [the BeeWare tutorial](https://beeware.github.com) for a guide on how to use Briefcase on your own projects.

Closing this ticket; but if you have any follow up questions, feel free to ask them here!

**Comment by AnissaHum** [comment]
Thank you for your quick answer, this was really helpful, I didn't think of this alternative.
