### ISSUE TITLE
Import Swift class registered as @objc with Rubicon-ObjC

### ISSUE THREAD

**Issue by AnissaHum** [beeware/rubicon-objc#152]
Hi, 
I am trying to use Rubicon inside an iOS app, containing not only Python and Objective-C code but also Swift.
I have a Swift class, registered as Objective-C as following: 
`@objc public class MyClass : NSObject`
My project contains a Bridging Header and also a *-Swift.h header.
When I try to import this class like this `MyClass = ObjCClass("MyClass")`, I get the following error: `NameError: ObjC Class 'b'MyClass'' couldn't be found.`.
However, when I try to do the same thing for an Objective-C file instead of Swift, it works fine.

Is there a way to use Swift files thanks to Rubicon ?

**Comment by freakboy3742** [comment]
I can't say I've tried anything with Swift, so I can't provide any detailed advice. However, I can think of two immediate causes:

1) There's some sort of name munging going on - Swift may add some something to the name of the Objective C classes that it exports, which is resolved by the compiler when you're using Objective C directly.
2) You haven't imported the library into your Python program. Before Python can use any Objective C symbol, the Swift/Objective C library needs to be loaded into your Python executable. You do this with the [load_library](https://rubicon-objc.readthedocs.io/en/latest/how-to/c-functions.html) method; you can see an example of this [being used in Rubicon's own test suite](https://github.com/beeware/rubicon-objc/blob/master/tests/__init__.py#L12).

**Comment by AnissaHum** [comment]
Thank you. I think that the problem comes from the first issue. 

In order to solve this problem, I've actually created an Objective-C class containing a class function, to instantiate my Swift class. He is what I did 
```@implementation MyBridingClass {
}
+(MyClass *) startMyClass{
MyClass * myClass = [[MyClass alloc] init];
return myClass;
}```
