### ISSUE TITLE
New release (0.4.0)?

### ISSUE THREAD

**Issue by dgelessus** [beeware/rubicon-objc#180]
It might be time for another release. Since the last one ([0.3.1 from 2019-05-25](https://pypi.org/project/rubicon-objc/0.3.1/)) we've had a bunch of fixes, the addition of the reference documentation, and some cleanups and/or removals. We also have our new automated GitHub Actions-based release workflow, which we have yet to test.

I think it would be best to make the next release version 0.4.0 rather than 0.3.2, because of my recent technically-breaking changes (#174) and the internal method calling change (#177), which could potentially break things in existing user code. (If I had planned any of this, I would have made a bugfix-only 0.3.2 release *before* submitting those changes...)

**Comment by freakboy3742** [comment]
Agreed - we're overdue for a release.

I think a minor bump is called for, too - although I must admit losing the symmetry of all the BeeWare projects being at (or near) 0.3 version numbers is more than a little annoying :-)

However, I started the process of cutting a release, and hit an interesting problem: twisted/towncrier#246

**Comment by freakboy3742** [comment]
Looks like current "best practice" is committing release notes to master; not exactly the ideal solution, but since another workaround doesn't look like it's forthcoming for the moment, I can live with it.

[0.4.0 has now been released](https://pypi.org/project/rubicon-objc/0.4.0/)

**Comment by dgelessus** [comment]
Thank you for taking care of the release!

I think pushing to master directly is fine as long as it's only for generating release notes and bumping the version number - there's not much that needs to be reviewed there. You need to do at least one manual push anyway to tag the release version.
