### ISSUE TITLE
CGColor cannot be found

### ISSUE THREAD

**Issue by saroad2** [beeware/rubicon-objc#190]
**Describe the bug**

*Important disclaimer*: I know nothing about ObjectiveC and this issue might be a mistake. If it is, sorry!

While trying to extend beeware/toga#1088 to Cocoa implementation, came across the need to import the `CGColor` class. I tried to use:

```python
CGColor = ObjCClass('CGColor')
```

But it raised the following errors:
```
File "/Users/sshadur/PycharmProjects/toga/src/cocoa/toga_cocoa/libs/appkit.py", line 180, in <module>
    CGColor = ObjCClass('CGColor')
  File "/Users/sshadur/PycharmProjects/toga/venv/lib/python3.7/site-packages/rubicon/objc/api.py", line 924, in __new__
    ptr, name = cls._new_from_name(name_or_ptr)
  File "/Users/sshadur/PycharmProjects/toga/venv/lib/python3.7/site-packages/rubicon/objc/api.py", line 827, in _new_from_name
    raise NameError("ObjC Class '%s' couldn't be found." % name)
NameError: ObjC Class 'b'CGColor'' couldn't be found.
```

I took a deeper look, and it seems like `CGColor` is too "basic" in order to be imported like that, and might be needed to add in rubicon/objc/api.py. I don't know what the right way of doing that.

**Environment:**
 - Operating System: MacOs Catalina 10.15.7 
 - Python version: 3.7.9
 - Software versions:
   - Toga: latest

**Comment by freakboy3742** [comment]
Thanks for the report; however, I don't think this is a bug in Rubicon.

Rubicon can't load *every* library that ships with macOS - there's just too many of them, and applications won't always needs all the libraries that are available. As a result, it only loads the C, ObjC and Foundation libraries - the libraries that can be considered the "core" of Objective C.

`CGColor` isn't a Foundation class; it's defined in CoreGraphics - so, you'll need to explicitly load the CoreGraphics library before you can reference `CGColor`. In the case of Toga, it [already does this](https://github.com/beeware/toga/blob/master/src/cocoa/toga_cocoa/libs/core_graphics.py#L21).  

On top of that: `CGColor` isn't an Objective C Class - [it's a typedef to a structure](https://developer.apple.com/documentation/coregraphics/cgcolorref?language=objc). This is very common in the Cocoa classes - if they start with `NS`, they're usually Objective C; if they start with `CG` or `CF`, they're usually C structures. As such, you don't access `CGColor` using `ObjCClass`; you need to build a CTypes structure. 

The Toga `toga_cocoa.libs.core_graphics` module has a couple of examples of structures that have been wrapped; exactly what is needed for CGColor will depend on what you want to do with the object. If you just need a placeholder, a simple wrapper around `c_void_p` (like `CGEventRef`) will be sufficient. If you want access to the attributes of CGColor, you'll need to build the full definition like `CGAffineTransform`.
