### ISSUE TITLE
Migrate Travis CI build from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by dgelessus** [beeware/rubicon-objc#191]
Our Travis CI builds are currently running on travis-ci.org, which [is being shut down on 2020-12-31](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom) (in two months) in favor of travis-ci.com.

For context: Travis CI has two separate (but functionally almost identical) services: travis-ci.org and travis-ci.com. Originally, all open-source projects used travis-ci.org, and all enterprise projects used travis-ci.com. In 2018, Travis CI [allowed open-source projects to use travis-ci.com as well](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps), and since then they have been slowly phasing out travis-ci.org in favor of travis-ci.com. However, existing open-source projects (such as rubicon-objc) continued to run on travis-ci.org, and for a while there was no good way to migrate existing projects from travis-ci.org to travis-ci.com - a migration option was available, but it required losing the project's entire Travis CI build history.

Thankfully, this situation has changed somewhat recently - Travis CI now supports [proper migration from travis-ci.org to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) with no loss of history or other information (except for build caches, but those will be regenerated with the next build). According to the docs, the migration is relatively straightforward - it's supposed to take only a few seconds and doesn't require any changes to the .travis.yml configuration. After the migration, we would only need to update our Travis CI badge in the README to point to travis-ci.com instead of travis-ci.org, and it might be necessary to update the PR check configuration in GitHub.

The docs still label this migration feature as "beta", which is a bit odd considering that travis-ci.org will be shut down in two months. The newsletter also isn't very clear about what will happen to projects that haven't migrated until then - will they be forcibly migrated on the shutdown date, or will they simply be deleted? To be safe, I think it would be better to manually migrate before the shutdown, despite the "beta" label. Or we could wait a few weeks to see if they un-beta the migration feature - but honestly considering how much the migration feature has been delayed already (IIRC it was originally planned to be released in late 2018?) I don't have very high hopes for that.

**Comment by freakboy3742** [comment]
Based on the [successful build of #192 appearing on travis-ci.com](https://travis-ci.com/github/beeware/rubicon-objc/builds/194215382), I'm going to call the migration a success. Thanks for keeping an eye on this so we didn't get a delightful surprise in a couple of months.

**Comment by dgelessus** [comment]
Yep, looks like builds are running and the old build history is also there on travis-ci.com - thank you for taking care of the migration!

Oddly, it seems that the history for old builds is now available on both travis-ci.org and travis-ci.com, and all the links in previous commit statuses still point to travis-ci.org. The build numbers for the same build are completely different on travis-ci.org and travis-ci.com, so there's no easy way to translate an old travis-ci.org URL to travis-ci.com. Perhaps they'll put redirects in place once travis-ci.org is shut down, otherwise I guess we'll have a lot of dead links in the commit statuses... At least you can still look at specific old builds by manually going through the build history on travis-ci.com.
