### ISSUE TITLE
Travis CI no longer provides unlimited free builds

### ISSUE THREAD

**Issue by dgelessus** [beeware/rubicon-objc#197]
Travis CI has [announced a new pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) today, and among other things they are no longer providing unlimited free builds for open-source projects. Existing open-source users are switched to a free trial plan, which means that you get 10,000 credits *once* - which is equivalent to 200 minutes of build time on macOS. That isn't all that much when you consider that one of our Travis builds normally takes about 5-6 minutes (for all different macOS versions combined) and you usually have multiple builds for each PR. If you do the math, that gives us maybe 10 PRs worth of Travis builds? The blog post also says:

> * We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.

I suppose we could try asking, but the way it's worded doesn't exactly sound like they have a lot of extra free capacity that they want to give away... And realistically, considering everything that's been happening with Travis CI recently, it's probably safer to move away completely to another CI service if possible. We already use GitHub Actions where possible, except for testing on old macOS versions (10.11 through 10.14) that only Travis CI provides - see #141 and #145.

Unfortunately it seems there are still no other CI services that provide a large number of older macOS versions like Travis does/did. GitHub Actions still only provides 10.15 (and recently 11.0), and both [AppVeyor](https://www.appveyor.com/docs/build-environment/#build-worker-images) and [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software) provide 10.14 and 10.15. This means that we probably have to do away with CI for all older macOS versions. We could use AppVeyor or Azure Pipelines to replace the macOS 10.14 Travis build, though I don't know if that's worth the effort for one macOS version... We could also keep Travis around, but only running the oldest available macOS (10.11), to make the most of the remaining free credits.

**Comment by freakboy3742** [comment]
Well darn. I guess the good news is that the only reason we're using TravisCI is to test older macOS and XCode versions for Rubicon. I'd definitely *prefer* to maintain testing for older macOS and XCode versions - but given we're now testing 2 versions in Github Actions, and Apple is pretty aggressive about pushing updates and forcing upgrades (especially with Xcode), and the competition doesn't really provide a viable alternative, I think I can probably live with only testing the versions that Apple is actively supporting, and remove our Travis CI builds.
