### ISSUE TITLE
Change the implementation of ObjCStrInstance

### ISSUE THREAD

**Issue by qqfunc** [beeware/rubicon-objc#451]
### What is the problem or limitation you are having?

~~Some methods like `ObjCStrInstance.__add__` use Objective-C methods now. However, converting to Python `str` and then adding is a faster way to do this. The same is perhaps true for the other methods.~~

This was my simple mistake. Using `ns_from_py()` at the end of the process required about the same time.

```python
>>> string = NSString.stringWithString("some string")
>>> timeit.timeit(lambda: string + string, number=10000)
>>> timeit.timeit(lambda: ns_from_py(str(string) + str(string)), number=10000)
```

These require approximately the same amount of time.

### Describe the solution you'd like

Just convert to Python `str` in the methods. Making their classes inherit [`collections.UserString`](https://docs.python.org/3/library/collections.html#userstring-objects) module might be beautiful way. (It's not a well considered idea.)

Postscript: As above, this was my mistake. However, I still suggest this plan.

### Describe alternatives you've considered

Maintain status quo.

**Comment by freakboy3742** [comment]
I'm a little confused about exactly what is being requested here.

As it currently stands, there's a clear line between `NSString` and `str`, and a clear point at which the strings change. On that basis, I don't think it's worth complicating both the interface and implementation - especially when, by your own analysis, it won't be any faster.

**Comment by qqfunc** [comment]
I am so sorry for the confusion.
This is now my vague idea and doesn't seem worth suggesting.
